using System;
using UnityEngine;

public class BattleCard : MonoBehaviour
{
    [SerializeField] private CardVisual _visual;

    /// <summary>The host-assigned identity, shared by all peers for this card's match lifetime.</summary>
    public Guid InstanceId { get; private set; }

    public bool IsInitialized => InstanceId != Guid.Empty;

    /// <summary>The runtime definition, or null until assigned.</summary>
    public CardDefinition Definition { get; private set; }
    public CardPlacementZoneView CurrentZone { get; internal set; }
    // Presentation facing relative to the zone anchor, independent of the local camera.
    public Quaternion PlacementRotationOffset { get; set; } = Quaternion.identity;
    private void OnDestroy()
    {
        if (CurrentZone != null) CurrentZone.RemoveView(this);
    }

    private void Awake()
    {
        if (_visual == null)
            _visual = GetComponentInChildren<CardVisual>();
    }

    /// <summary>
    /// Initializes this representation with the ID generated by the host for the logical card.
    /// The spawning/sync layer must deliver that same ID to every peer, including late joiners.
    /// Recreated representations must reuse the original ID for the remainder of the match.
    /// </summary>
    public void Initialize(Guid instanceId)
    {
        if (instanceId == Guid.Empty)
            throw new ArgumentException("A host-assigned card ID is required.", nameof(instanceId));

        if (IsInitialized && InstanceId != instanceId)
            throw new InvalidOperationException("A battle card's instance ID cannot be changed.");

        InstanceId = instanceId;
    }

    private void OnValidate()
    {
        if (_visual == null)
            _visual = GetComponentInChildren<CardVisual>();
    }

    /// <summary>
    /// Assigns the locally resolved definition selected by the host and refreshes the visual.
    /// The networking layer should transmit the definition ID, not the definition object.
    /// This method does not authorize or replicate gameplay changes.
    /// </summary>
    public void AssignDefinition(CardDefinition definition)
    {
        if (definition == null)
            throw new ArgumentNullException(nameof(definition));

        Definition = definition;

        if (_visual == null)
            _visual = GetComponentInChildren<CardVisual>();

        if (_visual != null)
            _visual.Bind(definition);
    }
}
