using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Mishi.Battle.Effects;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEngine;

namespace Mishi.EditorTools
{
    public static class KernelEffectAuthoring
    {
        public const string EffectDirectory = "Assets/Scripts/Battle/Effects";
        public const string CustomDirectory = EffectDirectory + "/Custom";
        public const string CatalogPath = EffectDirectory + "/GeneratedKernelEffectCatalog.cs";

        public static Type[] EffectTypes() => TypeCache.GetTypesDerivedFrom<KernelEffect>()
            .Where(t => !t.IsAbstract && !t.ContainsGenericParameters && t.Assembly == typeof(KernelEffect).Assembly)
            .OrderBy(t => t.FullName, StringComparer.Ordinal).ToArray();

        public static string SourcePath(Type type)
        {
            foreach (string guid in AssetDatabase.FindAssets(type.Name + " t:MonoScript", new[] { EffectDirectory }))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (AssetDatabase.LoadAssetAtPath<MonoScript>(path)?.GetClass() == type) return path;
            }
            return null;
        }

        [DidReloadScripts]
        private static void AfterCompilation() => EditorApplication.delayCall += RefreshAfterCompilation;
        private static void RefreshAfterCompilation()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode || EditorApplication.isCompiling) return;
            try { RegenerateCatalog(); }
            catch (Exception e) { Debug.LogError("内核效果注册失败，保留旧注册表：" + e.Message); }
        }

        [MenuItem("Mishi/Kernel Effects/Rebuild Registry")]
        public static void RegenerateCatalog()
        {
            var types = EffectTypes();
            foreach (var type in types)
                if (!type.IsPublic || type.GetConstructor(Type.EmptyTypes) == null)
                    throw new InvalidOperationException(type.FullName + " 必须为 public，且提供公开无参构造函数。");
            // Reject duplicate IDs before replacing the catalog. Runtime has the same guard.
            var effects = types.Select(type => (KernelEffect)Activator.CreateInstance(type)).ToArray();
            _ = new KernelEffectRegistry(effects);
            foreach (var effect in effects)
                if (!Regex.IsMatch(effect.Id, @"\A[A-Za-z][A-Za-z0-9_]*\z"))
                    throw new InvalidOperationException("无效效果 ID：" + effect.Id);
            string source = "// Generated by Mishi/Kernel Effects. Do not edit this catalog by hand.\n" +
                "namespace Mishi.Battle.Effects\n{\n    public static class GeneratedKernelEffectCatalog\n    {\n" +
                "        public static KernelEffect[] Create() => new KernelEffect[]\n        {\n" +
                string.Join("\n", types.Select(type => "            new global::" + type.FullName + "(),")) +
                "\n        };\n    }\n}\n";
            if (File.Exists(CatalogPath) && File.ReadAllText(CatalogPath).Replace("\r\n", "\n") == source) return;
            File.WriteAllText(CatalogPath, source, new UTF8Encoding(false));
            AssetDatabase.ImportAsset(CatalogPath);
        }

        public static string Create(string id, int template)
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode || EditorApplication.isCompiling)
                throw new InvalidOperationException("停止运行并等待编译完成后再创建效果。");
            if (!Regex.IsMatch(id ?? "", @"\A[A-Z][A-Za-z0-9_]{0,63}\z"))
                throw new ArgumentException("ID 使用大写英文字母开头的字母、数字或下划线，最长64位，例如 DrawExtra。");
            if (EffectTypes().Select(t => (KernelEffect)Activator.CreateInstance(t)).Any(e => string.Equals(e.Id, id, StringComparison.OrdinalIgnoreCase)))
                throw new ArgumentException("效果 ID 已存在：" + id);
            string path = CustomDirectory + "/" + id + "Effect.cs";
            if (File.Exists(path)) throw new IOException("文件已存在，不会覆盖：" + path);
            Directory.CreateDirectory(CustomDirectory);
            File.WriteAllText(path, BuildTemplate(id, template), new UTF8Encoding(false));
            AssetDatabase.ImportAsset(path);
            return path;
        }

        public static string BuildTemplate(string id, int template)
        {
            if (!Regex.IsMatch(id ?? "", @"\A[A-Z][A-Za-z0-9_]{0,63}\z")) throw new ArgumentException("Invalid ID.");
            string baseType = template == 1 ? "CardKernelEffect" : template == 2 ? "PlayerKernelEffect" : "KernelEffect";
            string signature = template == 1
                ? "protected override void Apply(EffectExecutionContext context, EffectInstruction instruction, NetworkTestMatch.Card card)"
                : template == 2 ? "protected override void Apply(EffectExecutionContext context, EffectInstruction instruction, int player)"
                : "public override void Execute(EffectExecutionContext context, EffectInstruction instruction)";
            return "using System;\n\nnamespace Mishi.Battle.Effects\n{\n" +
                "    // Stateless: store persistent match data in the execution context, never on this handler.\n" +
                "    public sealed class " + id + "Effect : " + baseType + "\n    {\n" +
                "        public override string Id => \"" + id + "\";\n" +
                "        public override string Description => \"待填写效果说明\";\n" +
                "        public override string LuaExample => @\"{ op = \"\"" + id + "\"\", amount = 1 }\";\n\n" +
                "        public override void Validate(EffectInstruction instruction, ICardEffectProvider definitions)\n        {\n" +
                "            base.Validate(instruction, definitions);\n" +
                "            // Replace this guard with parameter validation after implementing the effect.\n" +
                "            throw new NotSupportedException(\"" + id + " is not implemented yet.\");\n        }\n\n" +
                "        " + signature + "\n        {\n" +
                "            // Use context methods to preserve match invariants. See existing handlers.\n" +
                "            throw new NotImplementedException();\n        }\n    }\n}\n";
        }

        public static void SaveSource(string path, string expectedOriginal, string source)
        {
            string absolute = Path.GetFullPath(path);
            string root = Path.GetFullPath(EffectDirectory) + Path.DirectorySeparatorChar;
            if (!absolute.StartsWith(root, StringComparison.OrdinalIgnoreCase) || Path.GetExtension(absolute) != ".cs" ||
                absolute == Path.GetFullPath(CatalogPath)) throw new InvalidOperationException("只能编辑效果目录内的 C# 源文件。");
            if (File.ReadAllText(absolute) != expectedOriginal) throw new IOException("文件已被外部修改，请重新载入后编辑，避免覆盖。");
            File.WriteAllText(absolute, source, new UTF8Encoding(false));
            AssetDatabase.ImportAsset(path);
        }
    }
}
